SELECT T.*,T.ROWID FROM GET_VALUE_CFG T;
SELECT T.*,T.ROWID FROM SQL_CFG T;
SELECT T.*,T.ROWID FROM GET_VALUE_CFG_FIELD T where t.get_value_cfg_id = 1;
SELECT T.*,T.ROWID FROM GET_VALUE_SHOW_CFG T where t.get_value_cfg_id = 1;
SELECT T.*,T.ROWID FROM COMPONENT T;
SELECT T.*,T.ROWID FROM SQL_PARAM_CFG T where t.sql_id = 1;


--get sqlInfo
SELECT B.SQL_ID, B.SQL_TEXT, B.SQL_TYPE, B.CURSOR_INDEX
  FROM GET_VALUE_CFG A, SQL_CFG B
 WHERE A.GET_VALUE_ID = B.SQL_ID
   AND A.GET_VALUE_CFG_ID = ?;

SELECT T.*,T.ROWID FROM GET_VALUE_CFG_FIELD T WHERE T.CONFIG_SCRIPT IS NOT NULL;
   
SELECT upper(NAME) name,LABEL,WIDTH FROM GET_VALUE_CFG_FIELD WHERE GET_VALUE_CFG_ID = ? ORDER BY SORT_ID;

--GET_VALUE_SHOW_
SELECT T.GET_VALUE_CFG_ID,
       T.TITLE,
       T.IS_PAGE,
       T.PAGE_SIZE,
       T.IS_FORCEFIT,
       T.TOOLBAR_MENU_ID,
       T.RIGHT_MENU_ID,
       T.HIDDEN_COLUMNS,
       T.DBLCLICK,
       T.CONFIG_SCRIPT,
       T.IMPORT_JS,
       T.IMPORT_CSS,
       T.COLUMN_CFG_TYPE,
       T.DEFAULT_SEARCH,
       T.FILED_SEARCH,
       T.rowid       
  FROM GET_VALUE_SHOW_CFG T
 WHERE T.GET_VALUE_CFG_ID = 1;
 
 CRMII.TEST_PRO_SELECT_PRODUCTSELL ;
--获取搜索条件配置
SELECT T.SQL_ID,
       T.PARAM_NAME,
       T.COMP_ID,
       T.PARAM_TYPE,
       T.DATA_TYPE,
       T.IS_MULTIPLE,
       T.COMP_DS,
       T.COMP_CFG,
       T.PARAM_LABEL,
       T.SORT_ID,
       A.COMP_NAME,
       A.COMP_LABEL,
       A.DS_FUNCTION
  FROM SQL_PARAM_CFG T, COMPONENT A
 WHERE T.COMP_ID = A.COMP_ID
 and SQL_ID = (SELECT GET_VALUE_ID FROM GET_VALUE_CFG WHERE GET_VALUE_CFG_ID = ?);
 AND ((0=nvl(length(?),0) and 1=1) or (0<nvl(length(?),0) and sql_id = ?))
 
 
